# Generated by Django 3.0.4 on 2020-11-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201103_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='author',
            new_name='user',
        ),
    ]
